### ISSUE TITLE
Support Alternative and Configurable (pluggable) Diameter Load-Balancing Algorithms

### ISSUE THREAD

**Issue by brainslog** [RestComm/jdiameter#12]
Currently the peer selection is based on the rating of a peer in a certain realm. Different load-balancing techniques should be possible, such as round-robin, evaluating certain AVP values, etc.

These algorithms should be an extension point for the Mobicents Diameter Stack.

**Comment by ammendonca** [comment]
There are already alternative load balancer implementations, see [Weighted Round Robin](https://github.com/RestComm/jdiameter/blob/2e6bc7021dea69923237124be41ff019a294b89a/core/jdiameter/impl/src/main/java/org/jdiameter/client/impl/router/WeightedRoundRobinRouter.java) and [Weighted Least Connections](https://github.com/RestComm/jdiameter/blob/2e6bc7021dea69923237124be41ff019a294b89a/core/jdiameter/impl/src/main/java/org/jdiameter/client/impl/router/WeightedLeastConnectionsRouter.java).
