### ISSUE TITLE
AVP 22 not exist in the dictionary

### ISSUE THREAD

**Issue by abidmaria** [RestComm/jdiameter#176]
Dear Team ,

I am using the Mobicents library, and it appears that AVP code 22 is not present in the dictionary , do you have any suggestion or solution of this issue.
Spec :
`3GPP-User-Location-Info  AVP ( 22 )
This AVP indicates details of where the UE is currently located; e.g. SAI or CGI.
Reference: 3GPP TS 29.061-f50  [ View](http://www.3gpp.org/ftp/Specs/html-info/29061.htm)
Type:   OctetString
Mandatory Bit:   MUST NOT
Protection Bit:   MAY
Vendor ID:   10415
Value Length:   0 .. *`

Thank you

**Comment by aferreiraguido** [comment]
Hello Abidmaria, AVP 22 is defined as UTF8String and the inner fields as length, geolocation type plus another UTF8String with the geolocation information attribute, will vary from network to network, as that last field is vendor specific.

  <avpdefn name="3GPP-User-Location-Info" code="22" vendor-id="TGPP" mandatory="must" protected="may" may-encrypt="no" vendor-bit="must" >
    <type type-name="UTF8String" />
  </avpdefn>

**Comment by abidmaria** [comment]
Thank you @aferreiraguido  , I will make some changes and test them , then let you know how it goes , i plan to close this thread by tomorrow as the latest , again thank you for your support.

**Comment by abidmaria** [comment]
Fixed .
