### ISSUE TITLE
Memory leak in jDiameter

### ISSUE THREAD

**Issue by richardgood** [RestComm/jdiameter#23]
Hi

We've found a possible memory leak for Diameter session based RAs (e.g. Rx, Ro, Gx).  I want to see if the dev team agrees before raising it as a bug fix.

Looking just at Ro:
org.jdiameter.server.impl.app.ro.ServerRoSessionImpl.java

For CCA-U has Result-Code != SUCCESS the state machine does the following:

case SENT_UPDATE_RESPONSE:

RoCreditControlAnswer answer = (RoCreditControlAnswer) localEvent.getAnswer();
try {
if(isSuccess(answer.getResultCodeAvp().getUnsigned32())) {
// Current State: OPEN
// Event: CC update request received and successfully processed
// Action: Send CC update answer, debit used units, reserve new units, restart Tcc
// New State: OPEN
startTcc(answer.getValidityTimeAvp());
else {
// Current State: OPEN
// Event: CC update request received but not successfully processed
// Action: Send CC update answer with Result-Code != SUCCESS, debit used units
// New State: IDLE
// It's a failure, we wait for Tcc to fire -- FIXME: Alexandre: Should we?
}

Seen as how startTcc() is an empty method there doesn't seem to be any timer functionality.  So if an CCA-U has Result-Code != SUCCESS the activity stays in OPEN, never returns to IDLE and is never released.

I tested and this prevents the memory leak.

```
            // It's a failure, we wait for Tcc to fire -- FIXME: Alexandre: Should we?
```
-                                    newState = ServerRoSessionState.IDLE;
                               }
                           } catch (AvpDataException e) {
                               throw new InternalException(e);
                           }
                           dispatchEvent(localEvent.getAnswer());
-               if(newState != null) {
-                            setState(newState);
-           }
                          break;

This is for ServerRoSessionImpl.java.

The same should be done for all session based RAs (ServerGxSessionImpl.java, ServerRxSessionImpl.java)

**Comment by brainslog** [comment]
Hi @richardgood. Thanks for finding this!

Actually, there should be something in the startTcc method, there's a comment there stating that there's no Validity-Time AVP in 3GPP, but there's, just not at message top-level but inside MSCC AVP.

```
<Multiple-Services-Credit-Control> ::= < AVP Header: 456 >
                                       ...
                                     * [ G-S-U-Pool-Reference ]
                                       [ Validity-Time ]
                                       [ Result-Code ]
                                       ...
```

Let me know if you'd like to contribute a PR which uses the Validity-Time inside MSCC AVP.
