### ISSUE TITLE
 shutdown problem with TCP under Tomcat

### ISSUE THREAD

**Issue by shark300** [RestComm/jdiameter#27]
This issue is copied from googlecode (Issue 71 in jdiameter: shutdown problem with TCP under Tomcat)

What steps will reproduce the problem?
1.Configure for TCP
2.Run as webapp under tomcat
3.shutdown tomcat.

What is the expected output? What do you see instead?
Tomcat is not able to stop due to org.jdiameter.server.impl.io.tcp.NetworkGuard's Executor (binder) which is never shuted down.

What version of the product are you using? On what operating system?
1.6.0.FINAL

Please provide any additional information below.
You should call binder.shutdown() in e.g. cleanTask.

Here is our patch:

```
--- "a/3parties\\JDiameter\\core\\jdiameter\\impl\\src\\main\\java\\org\\jdiameter\\server\\impl\\io\\tcp\\NetworkGuard.java"
+++ "b/3parties\\JDiameter\\core\\jdiameter\\impl\\src\\main\\java\\org\\jdiameter\\server\\impl\\io\\tcp\\NetworkGuard.java"
@@ -275,6 +275,9 @@ public class NetworkGuard implements INetworkGuard {
         }
         serverSocket = null;
       }
+      if (binder != null) {
+        binder.shutdown();
+      }
     }

     @Override
```

**Comment by deruelle** [comment]
Hi @shark300 

Could you do a formal Pull Request following our [Open Source guidelines](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.mcjitemt6ng1) ?

Thanks in advance !

**Comment by shark300** [comment]
Hi @deruelle 

Ok.

**Comment by deruelle** [comment]
@shark300 

Thanks. can you also sign the contributor license agreement at http://www.telestax.com/open-source/#Contribute so we can accept the contribution ?

**Comment by shark300** [comment]
@deruelle I sent to you an email.
