### ISSUE TITLE
Avoid BufferOverflowException

### ISSUE THREAD

**Issue by shark300** [RestComm/jdiameter#28]
This issue is copied from googlecode (Issue 77 in jdiameter: Avoid BufferOverflowException)

What steps will reproduce the problem? 
1. Use client with high through output (600 TPS and each message ~1 KB) and TCP connection 
2. Stop and start Diameter server 

What is the expected output? What do you see instead? 
Expected: no exception and the connection is restored automatically. I get many BufferOverflowException and the connection lost. 

What version of the product are you using? On what operating system? 
1.6.0.FINAL CentOS 7 

Please provide any additional information below. 
When I added an extra condition into append(byte[]) in TCPTransportClient class I got the expected behavior. 

```
--- "a/3parties\\JDiameter\\core\\jdiameter\\impl\\src\\main\\java\\org\\jdiameter\\client\\impl\\transport\\tcp\\TCPTransportClient.java"
+++ "b/3parties\\JDiameter\\core\\jdiameter\\impl\\src\\main\\java\\org\\jdiameter\\client\\impl\\transport\\tcp\\TCPTransportClient.java"
@@ -345,7 +345,7 @@ public class TCPTransportClient implements Runnable {
    * @param data data to add
    */
   private void append(byte[] data) {
-    if (storage.position() + data.length >= storage.capacity()) {
+    if (storage.position() + data.length >= storage.capacity() || data.length > storage.remaining()) {
       ByteBuffer tmp = ByteBuffer.allocate(storage.limit() + data.length * 2);
       byte[] tmpData = new byte[storage.position()];
       storage.flip();

```

**Comment by brainslog** [comment]
This should have been fixed with #31, please reopen if you still experience it.
