### ISSUE TITLE
Ending Diameter activity explicitly from SBB

### ISSUE THREAD

**Issue by richardgood** [RestComm/jdiameter#33]
One thing I have noted is that unless Diameter activities are ended by their state machine (e.g. a CCR-T message is received) the activities never expire and there is no way for the SBB to remove them.

In the event of (non-Mobicents!) Diameter clients malfunctioning or rebooting this can cause a memory leak.

e.g.
Diameter Gx Client sends CCR-INIT for a certain IP address with session ID ABC
Diameter Gx Client malfunctions and sends CCR-INIT for the same IP address with session ID DEF
Gx Client never every terminate session ID ABC and it stays forever and is never free-ed.

The SBB application actually knows that session ID ABC needs to be removed when it receives a CCR-INIT for the same IP.
## If you edit the Diameter GX RA by adding to GxServerSessionActivityImpl.java:

public void delayedEndActivity() {
        this.setTerminateAfterProcessing(true);
        super.baseListener.startActivityRemoveTimer(getActivityHandle());
## void delayedEndActivity();

The SBB can explicitly end an activity if it needs to by calling delayedEndActivity on the activity.

This could be applied to all session based Diameter RAs

**Comment by chathsuom** [comment]
I guess this issue should be list under the RA's ?
https://github.com/RestComm/jain-slee.diameter

Thanks & Best Regards,
Gayan Gunapala
0450717020

**Comment by deruelle** [comment]
@chathsuom yes, indeed. Can you create an issue there linking to this one and fixing/udpating the RAs and do a pull request ?

@brainslog please review

**Comment by deruelle** [comment]
@chathsuom any news here ?

**Comment by xphudin** [comment]
Can I continue and PR ?

**Comment by deruelle** [comment]
@xphudin yes please.

**Comment by ammendonca** [comment]
Issue moved to [RestComm/jain-slee.diameter #26](https://github.com/RestComm/jain-slee.diameter/issues/26) via [**ZenHub**](https://www.zenhub.com/)
