### ISSUE TITLE
Update reference to the sources in documentation

### ISSUE THREAD

**Issue by baranchikovaleks** [RestComm/jdiameter#34]
Hi,

It seems like there is wrong reference here http://docs.telestax.com/category/diameter/ -> step2. There is reference to bitbucket (https://YOUR_USERNAME@bitbucket.org/telestax/telscale-diameter.git), but maybe it should be updated to https://github.com/RestComm/jdiameter/ ?

**Comment by deruelle** [comment]
@baranchikovaleks thanks for the report, we are currently moving to asciidoc for the documentation, see https://github.com/RestComm/jdiameter/tree/master/core/docs/sources-asciidoc/src/main/asciidoc and result at http://documentation.telestax.com/core/diameter/Diameter_User_Guide.html.

Those URLs have been solved here.

**Comment by deruelle** [comment]
Would you be interested in converting this tutorial on http://docs.telestax.com/category/diameter/ to asciidoc ?

**Comment by deruelle** [comment]
Migrated to http://documentation.telestax.com/core/tutorials/jdiameter-quick-telscale-diameter-performance-testing-using-seagull.html#perf. 

closing this issue
