### ISSUE TITLE
JMX Stack configuration

### ISSUE THREAD

**Issue by SummaNetworks** [RestComm/jdiameter#45]
The following issues have been found while trying to use the JMX stack configuration.
1. Local Peer add IP Address
   _LocalPeer_addIPAddress("127.0.0.1").
   Will trow: 
   java.lang.UnsupportedOperationException
   at java.util.AbstractList.add(AbstractList.java:148)
   at java.util.AbstractList.add(AbstractList.java:108)
   at org.mobicents.diameter.stack.DiameterStackMultiplexer._LocalPeer_addIPAddress(DiameterStackMultiplexer.java:545)
2. Network peers
   There is no method to retreive the existing list, so there is not an easy way to delete them.
3. Stack status
   There is not status indicator for the stack, so by simply calling stopStack there is no way knowing is that worked. 
4. getRealms from Network realms
   The method _Network_Realms_getRealms will only return the realms associated with the first result, which shall return all realms.

**Comment by xphudin** [comment]
hi @SummaNetworks 
For the 1st issue, It is cause by "Arrays.asList()",  in my thinking, it convert an fixed size array, and can not perform "add" function.
For me, the fix is:
             List <String> newIpAddressConfig = new ArrayList<String>(Arrays.asList(OldIpAddressConfig));

**Comment by xphudin** [comment]
Hi @SummaNetworks 
Sorry, the fix should be:
 List <Configuration> newIPAddressesConfig = new ArrayList <Configuration> (Arrays.asList(oldIPAddressesConfig));
      AppConfiguration newIPAddress = getClientConfiguration().add(OwnIPAddress, ipAddress);
      
      getMutableConfiguration().setChildren(OwnIPAddresses.ordinal(), (Configuration[])   newIPAddressesConfig.toArray(new Configuration[newIPAddressesConfig.size()]));

**Comment by xphudin** [comment]
Hi @SummaNetworks  I did 2 first issues and doing 2 last.
Thanks

**Comment by SummaNetworks** [comment]
Hi xphudin,

Thanks!!! so, you plan to do a PR with the fixes? 

We will really appreciate if you could dot it.

Miguel

**Comment by xphudin** [comment]
Hi @SummaNetworks  I did 2 first issues and doing 2 last.
Thanks

**Comment by SummaNetworks** [comment]
Thanks!!!!!

**Comment by xphudin** [comment]
hi @SummaNetworks , regarding 3rd- problem, when we call stopStack then stop function is called, which set state of stack "STOP". Is it enough? If needed, we can introduce new function like "isStopped" then check the state of stack is STOP or not?
Could you please give me your advices? 
Thanks

**Comment by SummaNetworks** [comment]
Hi xphudin,

Yes, any flag to know the status of the stack will suffice. Either isActive() or status().

**Comment by xphudin** [comment]
I do a PR, Can you please review it ?

**Comment by deruelle** [comment]
@brainslog can you review ?

**Comment by ammendonca** [comment]
Fixed with PR #68 (7349fc3)
