### ISSUE TITLE
DictionaryImpl does not provide original AVP type for AvpRepresentation

### ISSUE THREAD

**Issue by raidan2** [RestComm/jdiameter#51]
Looking at **org.jdiameter.common.impl.validation.DictionaryImpl** you may find it's impossible to get original AVP type from dictionary with

```
        // UTF8String and Time are special situations, we don't want to convert these.
        if (typeParent == null || typeParent.equals("") || typeName.equals("UTF8String") || typeName.equals("Time")) {
          typeParent = typeName;
        }
```

and 

```
            avpType = avpDefnChildElement.getAttribute("type-name");
            //FIXME: baranowb: why this is like that? This changes type of AVP to primitive ONE..? Checks against type dont make sense, ie to check for Address type...
            avpType = typedefMap.get(avpType);

```

As a result I cannot convert AVP into different format because I don't have type of this AVP (like it's an Address?).

May I suggest adding `String getOriginalType();` to **org.jdiameter.api.validation.AvpRepresentation** so anyone who interested in original type could get it?

Enums are also not included into AvpRepresentation. Shouldn't we add it?

**Comment by deruelle** [comment]
@brainslog can you answer this ?

**Comment by deruelle** [comment]
@raidan2 do you want to make a pull request for that ?

**Comment by aferreiraguido** [comment]
Hello @raidan2,
As per my understanding the type definition, works like a translator of a base type, you may define the type as a base one instead, with no parent definition. Enumeration is actually a sorted list of integers as well... if I misinterpreted your concern please let me know, happy to discuss, I wonder why that comment is there as well...

**Comment by brainslog** [comment]
@raidan2, I think it makes sense to add your suggestion to get the original type. It likely should have been the right way (and thus that comment) from the start, and have a getPrimitiveType() method instead. We should evaluate that option.

Regarding the `Enumerated` type, where do you see it missing ?

Please feel free to advance with a Pull Request for this if you feel like.

Thanks!

**Comment by xphudin** [comment]
Hi @raidan2 @brainslog , I looked into source code and saw that:
     - Avptype in AvpRepresentationImpl is passed by DictionaryImpl, right? but in DictionaryImpl, these type such as "Time" "UFT8String" are modified to respective its typeName.
     - Moving the introduction of getPrimitiveType() in AvpRepresentationImpl. I think its content may be like:
        String  getPrimitiveType(){
            if(this.type == "Time")
                 return "OctetString";
            ........ 
        }
    - Or should we have:
         private Map<String, String> primitiveTypedefMap = new HashMap<String, String>();
    in  DictionaryImpl, then keep the primitive avp types in this Map.

Could you please give me advice about this?

**Comment by raidan2** [comment]
@deruelle 
I'm sorry for such a delay in response. It's a little bit too much going on already.

@brainslog, please take a look at #69 
I was trying to make this description portable — i.e. transform to different format and return back, using only AvpRepresentation description.
It did work for me.

I'm fine to rename _getOriginalType()_ to  _getPrimitiveType()_ if you like.


@xphudin 
I personally don't think we should complicate this in any bit.

**Comment by deruelle** [comment]
@brainslog can you provide some feedback on this issue ?
