### ISSUE TITLE
Switch jdiameter library to the latest SCTP library

### ISSUE THREAD

**Issue by vetss** [RestComm/jdiameter#60]
SCTP lib is updating after adding new functionality into JSS7 stack. Now we have newer versions with netty support and we need to make support for them into jdiameter.

**Comment by vetss** [comment]
We have now two different versions of SCTP libs that correspond to different JSS7 versions:

1) JSS7 7.0 (that is released) that uses SCTP lib 1.7 https://mobicents.ci.cloudbees.com/view/SS7/job/Restcomm-SCTP/8/

2) JSS7 8.0 (not yet released) that uses SCTP lib 2.0 https://mobicents.ci.cloudbees.com/view/SS7/job/Restcomm-SCTP/10/
(it may be that we add extra little staff there and rebuild binaries, not 100% sure)

SCTP 1.7 supports only nio version (currnet diameter implementation)
SCTP 2.0 supports both nio and netty version to which we need to add support

So we need to create two jdiameter versions:
1) with SCTP 1.7 and nio usage
2) with SCTP 2.0 and netty usage

Version 1) just needs that we replace SCTP 1.6 in diameter mux binaries with SCTP 1.7. The most probable no code update is needed.

Version 2) demands
a) switching to SCTP version 2.0
b) code update to switch to netty version

**Comment by vetss** [comment]
Needed code update to switch to netty:

1) SCTP part: replace:
ManagementImpl -> NettySctpManagementImpl
AssociationImpl-> NettyAssociationImpl
and so on.
It is better also to have on board referenses to interfaces not to classes (like referens to Association instead of AssociationImpl). This is true for all classes instead of ManagementImpl / NettySctpManagementImpl

2) TCP part:
I see you do not use SCTP lib there, so no changes are needed
But it may be reasonable to reuse of SCTP lib also for this part

**Comment by vetss** [comment]
We have also an issue for switching TCP part for netty lib (without of using of SCTP lib for it)
https://github.com/RestComm/jdiameter/issues/35

**Comment by deruelle** [comment]
@brainslog can you comment on that ?

**Comment by deruelle** [comment]
tied to issue #59

**Comment by pmcgleenon** [comment]
Can you remove the jboss dependency that is introduced with the base sctp maven components?

jboss is being dragged in indirectly here and there appears to be no reason for the sctp component to require it

**Comment by deruelle** [comment]
That makes sense @pmcgleenon. Would you like to do a Pull Request for that ? That would speed it up.

**Comment by ammendonca** [comment]
Fixed with 400d639 on [SCTP-2.0-Netty](https://github.com/RestComm/jdiameter/tree/SCTP-2.0-Netty) branch.

Merging to master when jSS7 migrates to SCTP 2.0 as well.
