### ISSUE TITLE
Sending CER/CEA through APIs

### ISSUE THREAD

**Issue by arixion** [RestComm/jdiameter#88]
Hi all,

I am trying to make a simulator using the jdiameter libraries. Is there any way to send CER/CEA using APIs instead of being sent automatically by the library itself

**Comment by brainslog** [comment]
Hi @arixion,

Please use github issues only for reporting bugs, request for improvements or new features. For asking technical questions, please use [StackOverflow with "restcomm" tag](http://stackoverflow.com/questions/tagged/restcomm) or the [restcomm group](https://groups.google.com/forum/#!forum/restcomm), mostly suited for issues requiring broader discussion by the community.

Closing as invalid.
