### ISSUE TITLE
Settings for code style

### ISSUE THREAD

**Issue by bkrok** [RestComm/jdiameter#89]
Hello,
could you provide settings for code style formatting for IDEA or Netbeans IDE?

**Comment by ammendonca** [comment]
Hi @bkrok,

We will work on the codestyle for the required IDEs, I think Eclipse is able to import those from the rules at https://github.com/RestComm/jdiameter/blob/master/pom.xml#L123-L197.

Anyway, here are the rules we are using, while the files are not ready:

- No trailing spaces;
- Max line length of 160 chars;
- 2 space indentation (4 spaces for multi-line indentation);
- Braces around code blocks (and is not allowed single line statements);
- One statement per line;
- Star imports not allowed (except for static imports);
- No redundant imports allowed (duplicate, java.lang or same package imports);
- No unused imports;
- No illegal imports (eg: sun, junit.framework);
- Proper modifier order (public, protected, private, abstract, default, static, final, transient, volatile, synchronized, native, strictfp);
- No redundant modifiers;
- Left curly at EOL;
- No empty statements;
- No empty blocks for try/finally/if/else/switch;
- When overriding equals or hashCode, override the other one as well;
- Long constants should be defined with uppercase "L" and not lowercase (as "l" is similar to "1");
- Package annotations in the package-info.java file;
- If defining a covariant equals() (eg, equals(MyType)) method also override method equals(Object);
- Use Java style array type definition (type[] name) and not C (type name[]);

Thanks!
