### ISSUE TITLE
Origin and Destination Realm Problem

### ISSUE THREAD

**Issue by arifulislam2007** [RestComm/jdiameter#95]
Hello,
I'm very new to Diameter and trying to debug a code from one of my colleagues who left the company.  I'm facing one problem with origin and destination realm names.
I've configured different origin and destination realm names in the configuration file but the application is always sending origin-realm value for both origin and destination-realm to billing system in Sy request. Following is my configuration:

<?xml version="1.0"?>
<Configuration xmlns="http://www.jdiameter.org/jdiameter-server">

	<LocalPeer>
		<URI value="aaa://127.0.0.1:3868" />
		<IPAddresses>
			<IPAddress value="127.0.0.1" />
		</IPAddresses>
		**<Realm value="localRealm.com" />**
		<VendorID value="0" />
		<ProductName value="jDiameter" />
		<FirmwareRevision value="1" />
		<Applications>
			<ApplicationID>
				<VendorId value="10415" />
				<AuthApplId value="4" />
				<AcctApplId value="0" />
			</ApplicationID>
			<ApplicationID>
				<VendorId value="10415" />
				<AuthApplId value="16777302" />
				<AcctApplId value="0" />
			</ApplicationID>
			<ApplicationID>
				<VendorId value="10415" />
				<AuthApplId value="16777238" />
				<AcctApplId value="0" />
			</ApplicationID>				
		</Applications>
	</LocalPeer>
	<Parameters>
		<AcceptUndefinedPeer value="true" />
		<DuplicateProtection value="true" />
		<DuplicateTimer value="240000" />
		<UseUriAsFqdn value="true" />
		<QueueSize value="300000" />
		<MessageTimeOut value="60000" />
		<StopTimeOut value="10000" />
		<CeaTimeOut value="10000" />
		<IacTimeOut value="30000" />
		<DwaTimeOut value="10000" />
		<DpaTimeOut value="5000" />
		<RecTimeOut value="10000" />
	</Parameters>
	<Network>
		<Peers>
			<Peer name="aaa://10.10.1.144:3868" attempt_connect="true" rating="1" />
			<Peer name="aaa://10.10.0.8:3868" attempt_connect="true" rating="1"/>
		</Peers>
		<Realms>
			<Realm name=**"DestRealm1.com"** peers="10.10.1.144" local_action="PROXY" dynamic="false" exp_time="1">
				<ApplicationID>
					<VendorId value="10415" />
					<AuthApplId value="16777302" />
					<AcctApplId value="0" />
				</ApplicationID>	
			</Realm>
			<Realm name=**"DestRealm2.com"** peers="10.10.0.8" local_action="PROXY" dynamic="false" exp_time="1">
				<ApplicationID>
					<VendorId value="10415" />
					<AuthApplId value="16777302" />
					<AcctApplId value="0" />
				</ApplicationID>
			</Realm>
		</Realms>
	</Network>
	<Extensions />
</Configuration>

In the SLR message, both Origin and Destination Realm are sent as "localRealm.com". Any suggestion how to fix it?

Regards,
Arif

**Comment by ammendonca** [comment]
Hi @arifulislam2007 

The Destination-Realm is filled in your application code, when creating the request.

Please use github issues only for reporting bugs, request for improvements or new features. For asking technical questions, please use [StackOverflow with "restcomm" tag](http://stackoverflow.com/questions/tagged/restcomm) or the [restcomm group](https://groups.google.com/forum/#!forum/restcomm), mostly suited for issues requiring broader discussion by the community.

Closing as invalid.
